# Generated by Django 3.1.7 on 2021-05-28 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='upload_data/category_pics')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13)),
                ('price', models.IntegerField()),
                ('Payment_ID', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=400)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('sale', models.BooleanField(default=False)),
                ('ranking', models.IntegerField()),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOMMERCE.category')),
            ],
        ),
        migrations.CreateModel(
            name='Social_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=400)),
                ('whatsapp', models.CharField(max_length=400)),
                ('github', models.CharField(max_length=400)),
                ('instagram', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Products_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='upload_data/product_image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOMMERCE.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOMMERCE.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOMMERCE.product')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ECOMMERCE.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECOMMERCE.product')),
            ],
        ),
    ]
