# Generated by Django 3.1.7 on 2021-06-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOMMERCE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_picture', models.ImageField(upload_to='upload_data/customer_pics')),
                ('review', models.TextField()),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
