# Generated by Django 3.1.7 on 2021-06-01 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECOMMERCE', '0002_customerreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreview',
            old_name='ranking',
            new_name='rating',
        ),
    ]
