# Generated by Django 3.1.7 on 2021-06-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECOMMERCE', '0003_auto_20210601_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_links',
            name='facebook',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='github',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='instagram',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='whatsapp',
            field=models.URLField(max_length=400),
        ),
    ]
