# Generated by Django 3.1.7 on 2021-06-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECOMMERCE', '0004_auto_20210601_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_bill',
        ),
    ]
