# Generated by Django 3.1.7 on 2021-06-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECOMMERCE', '0005_auto_20210601_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordered_product',
            old_name='size',
            new_name='price',
        ),
    ]
