# Generated by Django 3.1.7 on 2021-06-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECOMMERCE', '0008_auto_20210602_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_size',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product_color',
        ),
        migrations.DeleteModel(
            name='Product_size',
        ),
    ]
